# network architecture
# encoder related
encoder: null

decoder: null
sed: true
stutternet: true
output_dim: 5

cmvn: global_cmvn
cmvn_conf:
  cmvn_file: 'data/train/global_cmvn'
  is_json_cmvn: true

dataset_conf:
    filter_conf:
        max_length: 4096
        min_length: 10
        token_max_length: 200
        token_min_length: 0
    resample_conf:
        resample_rate: 16000
    speed_perturb: false
    feats_type: mfcc
    mfcc_conf:
        num_mel_bins: 40
        frame_shift: 10
        frame_length: 25
        num_ceps: 40
        low_freq: 20
        high_freq: -400
        dither: 0.1
    spec_aug: true
    spec_aug_conf:
        num_t_mask: 2
        num_f_mask: 2
        max_t: 50
        max_f: 10
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    sort: true
    sort_conf:
        sort_size: 500  # sort_size should be less than shuffle_size
    batch_conf:
        batch_type: 'dynamic' # static or dynamic
        max_frames_in_batch: 30000

grad_clip: 5
accum_grad: 1
max_epoch: 100
log_interval: 50

optim: adam
optim_conf:
    lr: 0.001
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 1000
