# network architecture
# encoder related
frontend: wav2vec2
frontend_conf:
    frontend_conf:
        upstream: wav2vec2_local
        upstream_model_config:
        upstream_ckpt: /path/to/chinese-wav2vec2-base.converted.pt
    download_dir: ./hub
    multilayer_feature: False
    layer: 12

encoder: wav2vec2

decoder: null
sed: true
wav2vec2: true
output_dim: 5

cmvn: global_cmvn
cmvn_conf:
  cmvn_file: 'data/train/global_cmvn'
  is_json_cmvn: true
dataset_conf:
    filter_conf:
        max_length: 4096
        min_length: 10
        token_max_length: 200
        token_min_length: 0
    resample_conf:
        resample_rate: 16000
    feats_type: wav2vec2
    spec_aug: False
    spec_aug_conf:
        num_t_mask: 2
        num_f_mask: 2
        max_t: 50
        max_f: 10
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    sort: true
    sort_conf:
        sort_size: 500  # sort_size should be less than shuffle_size
    batch_conf:
        batch_type: 'dynamic' # static or dynamic
        max_frames_in_batch: 1800000

grad_clip: 5
accum_grad: 4
max_epoch: 100
log_interval: 50

optim: adam
optim_conf:
    lr: 0.00005
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 1000
