accum_grad: 8
cmvn_file: exp/20220506_u2pp_conformer_exp/global_cmvn
dataset_conf:
  batch_conf:
    batch_size: 96
    batch_type: dynamic
    max_frames_in_batch: 24000
  fbank_conf:
    dither: 1.0
    frame_length: 25
    frame_shift: 10
    num_mel_bins: 80
  filter_conf:
    max_length: 1200
    min_length: 10
    token_max_length: 100
    token_min_length: 1
  resample_conf:
    resample_rate: 16000
  shuffle: true
  shuffle_conf:
    shuffle_size: 20000
  sort: true
  sort_conf:
    sort_size: 2000
  spec_aug: true
  spec_aug_conf:
    max_f: 30
    max_t: 50
    num_f_mask: 2
    num_t_mask: 2
  speed_perturb: true
decoder: bitransformer
decoder_conf:
  attention_heads: 8
  dropout_rate: 0.1
  linear_units: 2048
  num_blocks: 3
  positional_dropout_rate: 0.1
  r_num_blocks: 3
  self_attention_dropout_rate: 0.1
  src_attention_dropout_rate: 0.1
encoder: conformer
encoder_conf:
  activation_type: swish
  attention_dropout_rate: 0.1
  attention_heads: 8
  causal: true
  cnn_module_kernel: 15
  cnn_module_norm: layer_norm
  dropout_rate: 0.1
  input_layer: conv2d
  linear_units: 2048
  normalize_before: true
  num_blocks: 12
  output_size: 512
  pos_enc_layer_type: rel_pos
  positional_dropout_rate: 0.1
  selfattention_layer_type: rel_selfattn
  use_cnn_module: true
  use_dynamic_chunk: true
  use_dynamic_left_chunk: false
grad_clip: 5
input_dim: 80
is_json_cmvn: true
log_interval: 500
max_epoch: 400
model_conf:
  ctc_weight: 0.3
  length_normalized_loss: false
  lsm_weight: 0.1
  reverse_weight: 0.3
optim: adam
optim_conf:
  lr: 2.5e-05
output_dim: 5538
scheduler: NoamHoldAnnealing
scheduler_conf:
  hold_steps: 250
  max_steps: 100000
  min_lr: 2.5e-06
  warmup_steps: 40
