accum_grad: 4
cmvn_file: exp/conformer/global_cmvn
dataset_conf:
  batch_conf:
    batch_type: dynamic
    max_frames_in_batch: 15000
  fbank_conf:
    dither: 0.0
    frame_length: 25
    frame_shift: 10
    num_mel_bins: 80
  filter_conf:
    max_length: 4096
    min_length: 10
    token_max_length: 200
    token_min_length: 0
  shuffle: true
  shuffle_conf:
    shuffle_size: 1500
  sort: true
  sort_conf:
    sort_size: 500
  spec_aug: true
  spec_aug_conf:
    max_f: 10
    max_t: 50
    num_f_mask: 2
    num_t_mask: 2
  speed_perturb: false
decoder: null
encoder: conformer
encoder_conf:
  activation_type: swish
  attention_dropout_rate: 0.0
  attention_heads: 4
  cnn_module_kernel: 15
  dropout_rate: 0.1
  input_layer: conv2d
  linear_units: 2048
  normalize_before: true
  num_blocks: 3
  output_size: 256
  pos_enc_layer_type: rel_pos
  positional_dropout_rate: 0.1
  selfattention_layer_type: rel_selfattn
  use_cnn_module: true
grad_clip: 5
input_dim: 80
is_json_cmvn: true
lfmmi_dir: ''
log_interval: 100
max_epoch: 100
optim: adam
optim_conf:
  lr: 0.001
output_dim: 5
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 1000
sed: true
