# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 100
  tensorboard_logdir: tblog
  seed: 1337

checkpoint:
  no_epoch_checkpoints: true
  best_checkpoint_metric: uer
  save_interval_updates: 5000 
  keep_interval_updates: 10

task:
  _name: audio_finetuning
  data: ???
  normalize: true
  labels: ltr
  max_sample_size: 480000
  min_sample_size: 10000

dataset:
  num_workers: 6
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true
  validate_interval_updates: 2500
  valid_subset: dev
  train_subset: train

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 4

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 320000
  lr: [0.0001]
  sentence_avg: true

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: wav2vec_ctc
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.5
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 5000
